name = "sewers.cc"
author = "fabra"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5dc2870e348f3797428c6b9c7234116e1f397dbad8eb7effc06f717115afea4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"

[options]
acceptable-game-versions = []
