name = "sewers.cc"
author = "fabra"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b26e4041bc0c7021e7d982878d9eba740287f2c2bdf7c7c3e7b1441a9ceb3125"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
