name = "sewers.cc"
author = "fabra"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee53b1d29ef6f160b47c61cb6ef1cc8a31bd3d2670399af89493cc607856405a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
