name = "sewers.cc"
author = "fabra"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeda221a63241463b4f1164b2e009c5f0d08dbefe647ea3707f5be56fb1b16e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
