name = "sewers.cc"
author = "fabra"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d38fa4da3bad6b6b79a3f285fa383017a5b89f1c6038c1321b52aca01a626d6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
